[2025-04-21T17:10:54.172+0000] {processor.py:186} INFO - Started process (PID=671) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:10:54.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:10:54.174+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:10:54.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:10:54.257+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:10:54.256+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:10:54.257+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:10:54.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.093 seconds
[2025-04-21T17:11:24.367+0000] {processor.py:186} INFO - Started process (PID=735) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:11:24.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:11:24.369+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:11:24.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:11:24.418+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:11:24.417+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:11:24.418+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:11:24.425+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.064 seconds
[2025-04-21T17:11:54.673+0000] {processor.py:186} INFO - Started process (PID=799) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:11:54.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:11:54.675+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:11:54.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:11:54.726+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:11:54.725+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:11:54.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:11:54.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.065 seconds
[2025-04-21T17:12:25.279+0000] {processor.py:186} INFO - Started process (PID=869) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:12:25.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:12:25.282+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:12:25.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:12:25.340+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:12:25.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:12:25.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:12:25.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.076 seconds
[2025-04-21T17:12:56.054+0000] {processor.py:186} INFO - Started process (PID=933) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:12:56.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:12:56.057+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:12:56.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:12:56.129+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:12:56.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:12:56.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:12:56.138+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.089 seconds
[2025-04-21T17:13:26.446+0000] {processor.py:186} INFO - Started process (PID=997) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:13:26.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:13:26.448+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:13:26.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:13:26.501+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:13:26.500+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:13:26.501+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:13:26.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.069 seconds
[2025-04-21T17:13:56.997+0000] {processor.py:186} INFO - Started process (PID=1061) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:13:56.997+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:13:56.999+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:13:56.999+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:13:57.048+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:13:57.047+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:13:57.049+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:13:57.056+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.063 seconds
[2025-04-21T17:14:27.157+0000] {processor.py:186} INFO - Started process (PID=1125) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:14:27.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:14:27.159+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:14:27.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:14:27.208+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:14:27.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:14:27.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:14:27.215+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.062 seconds
[2025-04-21T17:14:57.576+0000] {processor.py:186} INFO - Started process (PID=1189) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:14:57.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:14:57.579+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:14:57.579+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:14:57.627+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:14:57.627+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:14:57.628+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:14:57.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.064 seconds
[2025-04-21T17:15:27.709+0000] {processor.py:186} INFO - Started process (PID=1253) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:15:27.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:15:27.712+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:15:27.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:15:27.771+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:15:27.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:15:27.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:15:27.780+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.076 seconds
[2025-04-21T17:15:58.259+0000] {processor.py:186} INFO - Started process (PID=1317) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:15:58.260+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:15:58.262+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:15:58.262+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:15:58.315+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:15:58.314+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:15:58.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:15:58.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.069 seconds
[2025-04-21T17:16:03.396+0000] {processor.py:186} INFO - Started process (PID=1320) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:16:03.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:16:03.399+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:03.399+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:16:03.410+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:03.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 125, in <module>
    fetch_book_data_task = PythonOperator(
                           ^^^^^^^^^^^^^^
NameError: name 'PythonOperator' is not defined
[2025-04-21T17:16:03.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:16:03.423+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.032 seconds
[2025-04-21T17:16:18.494+0000] {processor.py:186} INFO - Started process (PID=1376) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:16:18.495+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:16:18.496+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:18.496+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:16:18.504+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:16:18.549+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:18.549+0000] {override.py:1912} INFO - Created Permission View: can edit on DAG:fetch_and_store_amazon_books
[2025-04-21T17:16:18.552+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:18.552+0000] {override.py:1912} INFO - Created Permission View: can read on DAG:fetch_and_store_amazon_books
[2025-04-21T17:16:18.554+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:18.554+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG:fetch_and_store_amazon_books
[2025-04-21T17:16:18.556+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:18.556+0000] {override.py:1912} INFO - Created Permission View: can create on DAG Run:fetch_and_store_amazon_books
[2025-04-21T17:16:18.557+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:18.557+0000] {override.py:1912} INFO - Created Permission View: menu access on DAG Run:fetch_and_store_amazon_books
[2025-04-21T17:16:18.558+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:18.558+0000] {override.py:1912} INFO - Created Permission View: can read on DAG Run:fetch_and_store_amazon_books
[2025-04-21T17:16:18.560+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:18.560+0000] {override.py:1912} INFO - Created Permission View: can delete on DAG Run:fetch_and_store_amazon_books
[2025-04-21T17:16:18.560+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:18.560+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-21T17:16:18.564+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:18.564+0000] {dag.py:3262} INFO - Creating ORM DAG for fetch_and_store_amazon_books
[2025-04-21T17:16:18.567+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:18.567+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to None, run_after=None
[2025-04-21T17:16:18.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.084 seconds
[2025-04-21T17:16:24.561+0000] {processor.py:186} INFO - Started process (PID=1377) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:16:24.562+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:16:24.563+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:24.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:16:24.572+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:16:24.581+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:24.580+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-21T17:16:24.593+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:24.592+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to None, run_after=None
[2025-04-21T17:16:24.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.046 seconds
[2025-04-21T17:16:54.788+0000] {processor.py:186} INFO - Started process (PID=1441) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:16:54.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:16:54.790+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:54.790+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:16:54.797+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:16:54.811+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:54.810+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-21T17:16:54.821+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:16:54.821+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to None, run_after=None
[2025-04-21T17:16:54.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.046 seconds
[2025-04-21T17:17:24.950+0000] {processor.py:186} INFO - Started process (PID=1505) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:17:24.950+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:17:24.952+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:17:24.951+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:17:24.955+0000] {processor.py:925} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:17:24.962+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:17:24.962+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-04-21T17:17:24.970+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:17:24.970+0000] {dag.py:4180} INFO - Setting next_dagrun for fetch_and_store_amazon_books to None, run_after=None
[2025-04-21T17:17:24.976+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.029 seconds
[2025-04-21T17:17:54.414+0000] {processor.py:186} INFO - Started process (PID=1569) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:17:54.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:17:54.417+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:17:54.416+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:17:54.467+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:17:54.466+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:17:54.467+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:17:54.474+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.066 seconds
[2025-04-21T17:18:24.604+0000] {processor.py:186} INFO - Started process (PID=1632) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:18:24.605+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:18:24.607+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:18:24.607+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:18:24.659+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:18:24.659+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:18:24.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:18:24.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.070 seconds
[2025-04-21T17:18:54.999+0000] {processor.py:186} INFO - Started process (PID=1696) to work on /opt/airflow/dags/dag.py
[2025-04-21T17:18:55.000+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2025-04-21T17:18:55.002+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:18:55.001+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2025-04-21T17:18:55.052+0000] {logging_mixin.py:190} INFO - [2025-04-21T17:18:55.051+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-04-21T17:18:55.052+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2025-04-21T17:18:55.060+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.066 seconds
